### ISSUE TITLE
Impersonating ldap group members is not possible

### ISSUE THREAD

**Issue by SergioBertolinSG** [owncloud/impersonate#66] opened 2017-10-10 08:30 UTC
### Steps to reproduce

0. Having impersonate and ldap apps enabled.
1. Set up a ldap server with groups and members of the groups.
2. As admin, go to user management and give group admin privileges to one ldap user 'ldapuser1', member of a group 'ldapgroup1'. Having 'ldapgroup1' more members.
3. As 'ldapuser1' go to users page.
4. Try to impersonate another member of 'ldapgroup1'.

### Expected behaviour
'ldapuser1' can impersonate the other members of 'ldapgroup1'.

### Actual behaviour
'ldapuser1' cannot impersonate the other members of 'ldapgroup1'.

![screen shot 2017-10-10 at 10 42 12](https://user-images.githubusercontent.com/9048796/31377291-d026917a-ada7-11e7-8702-6f1af2d791c5.png)

### Server configuration

**Operating system**:
Ubuntu 16.04

**Web server:**
Apache

**Database:**
MySQL

**PHP version:**
7.0

**ownCloud version:** (see ownCloud admin page)
current Master
{"installed":"true","maintenance":"false","needsDbUpgrade":"false","version":"10.0.3.3","versionstring":"10.0.3","edition":"Community","productname":"ownCloud"}

**Updated from an older ownCloud or fresh install:**
Fresh

**The content of config/config.php:**

```

```

**Are you using external storage, if yes which one:** local/smb/sftp/...
No.

**Are you using encryption:** 
No.

**Logs**
```
```

### Client configuration

**Browser**
Firefox

cc @sharidas

**Comment by pmaier1** [comment] 2017-11-06 16:14
Moving to next version as we need a release now.

**Comment by PVince81** [comment] 2017-11-13 09:32
@sharidas any update ?

**Comment by sharidas** [comment] 2017-11-15 08:39
Below is the change I have observed with master core (https://github.com/owncloud/core/commit/bbdc0fcdc4dd0315a4681efc0ae001ba1fa01cc9 ) and impersonate change made recently for core change (https://github.com/owncloud/impersonate/pull/80):
1) Enabled impersonate and ldap
2) Tried to create users and groups with the script: https://github.com/owncloud/administration/blob/master/ldap-testing/batchCreateUsersInGroups.php
3) Now I was able to see in the phpldapadmin there were users and groups created.
4) Tried to configure the ldap setup in the user authentication section in the settings.
5) Selected the groups `Army0`
6) Attaching user auth page where I selected `Army0 and `group1` ( group1 was created ) : 
![userauthpage](https://user-images.githubusercontent.com/3600427/32826319-f54eebe6-ca0d-11e7-94a6-9cd892ea74ba.png)
7) Now tried to navigate to admin user page: 
![adminuserpage](https://user-images.githubusercontent.com/3600427/32826352-0ea3c6fc-ca0e-11e7-92e3-7a769bc62329.png)
8) Login as zombie5 ( one of the users ) and tried to navigate to users page. As zombie5 is the group admin for `Army0` : 
![zombie5userpage](https://user-images.githubusercontent.com/3600427/32826401-3e7cc676-ca0e-11e7-83f5-c0ff6680a687.png)
9) Impersonate to user zombie6: 
![impersonatedtozombie6](https://user-images.githubusercontent.com/3600427/32826433-585b75e2-ca0e-11e7-8488-f5dffb0e4a43.png)
10) From the admin page also I was able to impersonate the zombie users.

One possibility I am thinking is if the user misses step 6 of impersonate setting in the user auth page mentioned ( or the settings page where impersonate settings available in previous version ), then 
screenshot shared at: https://github.com/owncloud/impersonate/issues/66#issue-264140597 is expected.

**Comment by sharidas** [comment] 2017-11-15 08:41
@SergioBertolinSG Let me know your opinion.

**Comment by patrickjahns** [comment] 2017-12-06 10:46
Is this fixed by #80?

**Comment by patrickjahns** [comment] 2017-12-06 10:47
Is this fixed in master? Or still needing a fix?

**Comment by sharidas** [comment] 2017-12-06 10:51
I am not able to reproduce this issue. For me this works. QA needs to tell me under what circumstance this issue was reproduced. With the steps mentioned in the ticket its not reproducible in the master branch of the app.

**Comment by patrickjahns** [comment] 2017-12-07 14:52
Moved to development to triage this issue further

**Comment by SergioBertolinSG** [comment] 2017-12-11 12:09
@sharidas OK I can impersonate ldap users without problems. 

I think I missed this step:

> One possibility I am thinking is if the user misses step 6 of impersonate setting in the user auth page mentioned

**Closed** 2017-12-11 12:09 UTC
Labels: bug, sev2-high
